#  - - 常规选项 - - # 

# url是完整的网站网址
# baseurl是没有主机名的网站的URL

# 如果要构建一个简单的GitHub用户页面（http://username.github.io），请使用以下设置：

url: "https://www.cxanimeclub.ml"
baseurl: ""

#  网站标题
title: 岑溪市动漫社

# 网站简介
description: 

#  --- 导航栏选项 --- # 

#  导航栏中的链接列表
navbar-links:
  关于: "aboutme"
  推荐站点:
    - 哔哩哔哩: "http://www.bilibili.com"
    - GitHub: "https://pages.github.com/"

# 要在导航栏中显示的图像 - 图像必须是正方形（宽度=高度）
# 如果您不想在导航栏中显示图像，请删除此参数

#百度统计
baidu:
    id: f0e8a535a5468bdefec1e06306ef2652


avatar: "/img/avatar-icon.png"

# 如果您想在左上角放置图像徽标而不是标题文字，
# 然后指定以下参数
# title-img：/ path / to / image

# ---背景颜色/图像选项---# 

# 个性化您网站的颜色。 颜色值可以是任何有效的CSS颜色

navbar-col: "# F5F5F5"
navbar-text-col: "#000000"
navbar-children-col: "# F5F5F5"
page-col: "#FFFFFFF"
link-col: "#008AFF"
#复制字体颜色
hover-col: "#4169E1"
footer-col: "#FFFFFFF"
footer-text-col: "#000000"
footer-link-col: "# 404040"

# 或者，可以将导航栏，页脚和页面背景设置为使用背景图像
# 而不是颜色

#头像上方
#navbar-img: "/img/hello_world.jpeg"
#最底
#footer-img: "/img/hello_world.jpeg"
#页面背景
page-img: "/img/background.png"

# ---页脚选项---# 

# 更改所有这些值或删除不需要的值。
# 重要提示：您必须保留"名称"参数，您可以删除其他所有内容

author:
  name: 服务器提供

#选择您的活动社交网络链接。
#取消注释要在页脚中显示的链接，并将信息添加到每个链接。
#您可以重新排序项目以定义链接顺序。
#如果你想添加一个不在这里的新链接，你还需要编辑文件_data / SocialNetworks.yml

social-network-links:
  rss: true
  email: "luvse@foxmail.com"
#  facebook: daattali
  github: GreenChennai
#  twitter: daattali
#   reddit: yourname
#   google-plus: +DeanAttali
#   linkedin: daattali
#   xing: yourname
#   stackoverflow: "3943160/daattali"
#   snapchat: deanat78
#   instagram: deanat78
#   youtube: user/deanat78
#   spotify: yourname
#   telephone: +14159998888
#   steam: deanat78
#   twitch: yourname
#   yelp: yourname

#  选择要在帖子中显示的共享链接
share-links-active:
  twitter: false
  facebook: false
  google: true
  linkedin: false

#如何在页脚中显示网站链接
#如果您不想在页脚中添加链接，请将其删除

url-pretty: "Github"  #  eg. "https://github.com"

#---网站统计科---#

#填写您的Google Analytics（分析）gtag.js ID，以使用gtag跟踪您的网站
#gtag：""

#填写您的Google Analytics ID，使用GA跟踪您的网站
# 谷歌分析： ""

#Google Tag Manager ID
#gtm：""

#Matomo（又名Piwik）网站统计
#取消注释以下部分以启用Matomo。 选择退出参数控制
#是否要允许用户选择退出跟踪。

#matomo：
#site_id："9"
#uri："demo.wiki.pro"
#opt-out：true

# - - 注释 - - #

#如果你想支持Disqus评论，请填写你的Disqus短名称（不是用户名）
#disqus：""

#要使用Facebook评论，请填写Facebook App ID
#fb_comment_id：""

#---其他---#

#Facebook App ID
#fb_app_id：""

#摘录字长
#将摘录截断到索引页面上指定的单词数

excerpt_length: 50

# 用于分隔HTML文档标题中的网站标题和描述的字符
# 和RSS提要标题
title-separator: ""

# ---不需要触摸下面的任何东西（但如果你愿意，你可以） - # 

# 输出选项（有关Jekyll网站的更多信息）

timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# 默认YAML值（有关Jekyll网站的更多信息）
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  #  add comments to all blog posts
      social-share: true #  add social media sharing buttons to all blog posts
  -
    scope:
      path: "" #  all files
    values:
      layout: "page"
      show-avatar: true

#  使用标签索引页面并在每个帖子上点击标签
link-tags: true

# 从生产站点中排除这些文件
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

#  prose.io配置
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
